//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.Membership = new HashSet<Membership>();
            this.Operation = new HashSet<Operation>();
            this.Role = new HashSet<Role>();
        }
    
        public int IDApplication { get; set; }
        public System.Guid UniqueID { get; set; }
        public string ApplicationName { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public bool Enabled { get; set; }
        public bool DefaultExterno { get; set; }
        public bool Visible { get; set; }
    
        public virtual ICollection<Membership> Membership { get; set; }
        public virtual ICollection<Operation> Operation { get; set; }
        public virtual ICollection<Role> Role { get; set; }
    }
}
