//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int idBitacora { get; set; }
        public Nullable<byte> idAccion { get; set; }
        public string nbUsuarioModifico { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string datoAnterior { get; set; }
        public string datoNuevo { get; set; }
    
        public virtual CatBitacoraAccion CatBitacoraAccion { get; set; }
    }
}
