//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosFiscales
    {
        public int IdDatosFiscales { get; set; }
        public int Fk_IdUser { get; set; }
        public string Escritura { get; set; }
        public System.DateTime FechaEscritura { get; set; }
        public string FolioReal { get; set; }
        public string NumeroLibro { get; set; }
        public string Tomo { get; set; }
        public string Volumen { get; set; }
        public string Foja { get; set; }
        public string Seccion { get; set; }
        public string NombreNotario { get; set; }
        public string ApellidoPaternoNotario { get; set; }
        public string ApellidoMaternoNotario { get; set; }
        public string NumeroNotario { get; set; }
        public string CiudadNotario { get; set; }
        public string DistritoNotario { get; set; }
        public string IdGeneroNotario { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<System.DateTime> FechaUltimoCambio { get; set; }
        public bool EstatusRegistro { get; set; }
        public Nullable<bool> RegistroValidado { get; set; }
    
        public virtual User User { get; set; }
    }
}
