//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public Operation()
        {
            this.RoleOperation = new HashSet<RoleOperation>();
        }
    
        public int IDOperation { get; set; }
        public string OperationName { get; set; }
        public int IDApplication { get; set; }
        public string Description { get; set; }
        public string IDExterno { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<RoleOperation> RoleOperation { get; set; }
    }
}
