//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_Identificacion
    {
        public int IdRelIdentificacion { get; set; }
        public int IdTipoRel { get; set; }
        public int Fk_IdRelRegistro { get; set; }
        public int FK_IdIdentificacionExpide { get; set; }
        public string NumeroIdentificacion { get; set; }
        public bool EstatusRegistro { get; set; }
        public Nullable<int> Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
