//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_RoleContentModelAlfresco
    {
        public int IdRoleContentModel { get; set; }
        public int Fk_IdContentModelA { get; set; }
        public int Fk_idRole { get; set; }
        public bool EstatusRegistro { get; set; }
        public int Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Cat_ContentModelAlfresco Cat_ContentModelAlfresco { get; set; }
        public virtual Role Role { get; set; }
    }
}
