//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_UserDomicilio
    {
        public int IdRelUserDom { get; set; }
        public int Fk_IdTipoDom { get; set; }
        public int FkIdUser { get; set; }
        public int FkIdDomicilio { get; set; }
        public bool EstatusRegistro { get; set; }
    
        public virtual Domicilio Domicilio { get; set; }
        public virtual User User { get; set; }
    }
}
