//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_FR_INM
    {
        public string RfiEdo { get; set; }
        public string RfiConsecutivo { get; set; }
        public string RfiDigVerificador { get; set; }
        public int IdFolioReal { get; set; }
        public string FECHA { get; set; }
    }
}
