//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE_PDR
    {
        public int iduser { get; set; }
        public string username { get; set; }
        public int Admin { get; set; }
        public int Inventario { get; set; }
        public int ResponsableInmobiliario { get; set; }
        public int Capturista { get; set; }
        public int Catastro { get; set; }
        public int Cedoc { get; set; }
        public int DGPGI { get; set; }
        public int Catalogos { get; set; }
        public int Especialista { get; set; }
        public int Subdirector { get; set; }
        public int DGAPIF { get; set; }
        public int Supervisor { get; set; }
        public int Consulta { get; set; }
        public int Busqueda { get; set; }
        public int UsuarioParametricos { get; set; }
        public int Juridico { get; set; }
        public int JefeDepto { get; set; }
        public int Director { get; set; }
        public int UsuarioSAEF { get; set; }
    }
}
