//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepresentanteLegal
    {
        public RepresentanteLegal()
        {
            this.Rel_UserRL = new HashSet<Rel_UserRL>();
        }
    
        public int IdRepresentanteLegal { get; set; }
        public string RFC { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Cargo { get; set; }
        public string IdGenero { get; set; }
        public Nullable<int> IdPais { get; set; }
        public string CorreoRL { get; set; }
        public int IdTipoIdentificacion { get; set; }
        public string NumeroIdentificacion { get; set; }
        public string NumeroPoder { get; set; }
        public System.DateTime FechaPoder { get; set; }
        public string NombreNotario { get; set; }
        public string ApellidoPaternoNotario { get; set; }
        public string ApellidoMaternoNotario { get; set; }
        public string NumeroNotarioPoder { get; set; }
        public string DistritoNotarioPoder { get; set; }
        public string IdGeneroNotarioPoder { get; set; }
        public string CiudadPoderNotarial { get; set; }
        public Nullable<bool> RegistroValidado { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<System.DateTime> FechaUltimoCambio { get; set; }
        public bool EstatusRegistro { get; set; }
    
        public virtual ICollection<Rel_UserRL> Rel_UserRL { get; set; }
    }
}
