//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleOperation
    {
        public int IDRoleOperation { get; set; }
        public int IDRole { get; set; }
        public int IDOperation { get; set; }
    
        public virtual Operation Operation { get; set; }
        public virtual Role Role { get; set; }
    }
}
