//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public int IdTelefono { get; set; }
        public int Fk_IdUser { get; set; }
        public int Fk_IdTipoTelefono { get; set; }
        public string Lada { get; set; }
        public string Telefono1 { get; set; }
        public string Extension { get; set; }
        public bool EsPrincipal { get; set; }
        public Nullable<System.DateTime> FechaUltimoCambio { get; set; }
        public bool EstatusRegistro { get; set; }
        public Nullable<int> Fk_IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual User User { get; set; }
    }
}
