//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_password
    {
        public int IDUser { get; set; }
        public string password_open { get; set; }
        public string password_encrypted { get; set; }
        public Nullable<bool> flag { get; set; }
    }
}
