//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserConfirmation
    {
        public int IDUserConfirmation { get; set; }
        public int IDUser { get; set; }
        public System.Guid GUID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
